version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django-app
    expose:
      - "8000"  # Expose port 8000 to the Nginx container
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certbot/www:/var/www/certbot:ro
      # - ./nginx/certbot/conf:/etc/letsencrypt
    # environment:
    #   - IP_ADDRESS=127.0.0.1
    command: ["nginx", "-g", "daemon off;"]
 
volumes:
  postgres_data:
    driver: local