# Generated by Django 5.1.4 on 2025-01-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_remove_user_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lobby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
