# Generated by Django 5.1.4 on 2025-01-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_user_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
