# Generated by Django 5.1.4 on 2025-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_42',
            field=models.BooleanField(default=False),
        ),
    ]
