# Generated by Django 4.2.18 on 2025-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcendence", "0005_user_user_42"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_prt_key",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
