# Generated by Django 5.1.3 on 2024-12-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0006_user_photo_alter_user_description_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
