# Generated by Django 5.1.3 on 2024-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/profile_standard.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
