# Generated by Django 5.1.4 on 2025-01-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0017_user_is_online_user_last_activity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
