# Generated by Django 5.1.4 on 2025-01-03 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0018_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
