# Generated by Django 5.1.4 on 2025-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0020_alter_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
