# Generated by Django 5.1.4 on 2025-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0023_alter_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='owner',
        ),
    ]
