# Generated by Django 5.1.4 on 2025-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0024_remove_chatgroup_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friend_request_direct'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('sender__lt', models.F('receiver'))), fields=('sender', 'receiver'), name='unique_friend_request_inverse'),
        ),
    ]
